services:
  web:
    image: actualbudget/actual-server@sha256:552beab3dec8c93d46b8b9245612d63c3f123b8a45063a474f53e229b17621d3 # tag: 26.9.0
    volumes:
      - {type: volume, source: data, target: /data}
volumes:
  data: {}
