services:
  web:
    image: ghcr.io/advplyr/audiobookshelf@sha256:180acad33d69c99ed208676465d8edcb268fa46967735579a7810859885b1a8e # tag: 2.36.0
    environment:
      TZ: "UTC"
    volumes:
      - {type: volume, source: config, target: /config}
      - {type: volume, source: metadata, target: /metadata}
      - {type: volume, source: audiobooks, target: /audiobooks}
      - {type: volume, source: podcasts, target: /podcasts}
volumes:
  audiobooks: {}
  config: {}
  metadata: {}
  podcasts: {}
