services:
  ollama:
    image: ollama/ollama@sha256:684d8674b4315fa18f4f0e973a118ec2652ed96f67563277839985175858e0ba # tag: 0.34.0
    environment:
      OLLAMA_KEEP_ALIVE: "5m"
    volumes:
      - {type: volume, source: models, target: /root/.ollama}
  web:
    image: ghcr.io/open-webui/open-webui@sha256:41daa0cf2561a5d4c8d1ff31ee2a98d93ab4d3ac2605cac69366ff6a3374a933 # tag: v0.11.3
    environment:
      OLLAMA_BASE_URL: "http://ollama:11434"
      ENABLE_SIGNUP: "true"
      DEFAULT_USER_ROLE: "pending"
      SCARF_NO_ANALYTICS: "true"
      DO_NOT_TRACK: "true"
      ANONYMIZED_TELEMETRY: "false"
    depends_on:
      ollama: {condition: service_started}
    volumes:
      - {type: volume, source: data, target: /app/backend/data}
volumes:
  data: {}
  models: {}
