services:
  web:
    image: deluan/navidrome@sha256:a384948b81bd1529986c5960169e7fc4fa00f46bde6bd517971a4c36671db2af # tag: 0.64.0
    environment:
      ND_SCANSCHEDULE: "1h"
      ND_LOGLEVEL: "info"
      ND_MUSICFOLDER: "/music"
      ND_DATAFOLDER: "/data"
    volumes:
      - {type: volume, source: data, target: /data}
      - {type: volume, source: music, target: /music}
volumes:
  data: {}
  music: {}
