services:
  web:
    image: louislam/uptime-kuma@sha256:917318f9d7be5257f43ba412c766a473be336eb451d70744f3b482d0c3997c0e # tag: 2.5.4
    volumes:
      - {type: volume, source: data, target: /app/data}
volumes:
  data: {}
